<?php

declare(strict_types=1);

return [
	'routes' => [
		['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
		['name' => 'page#admin', 'url' => '/admin', 'verb' => 'GET'],
		['name' => 'page#adminMembers', 'url' => '/admin-haeuser-personen', 'verb' => 'GET'],
		['name' => 'page#bankverbindung', 'url' => '/bankverbindung', 'verb' => 'GET'],
		['name' => 'page#vorschreibungen', 'url' => '/vorschreibungen', 'verb' => 'GET'],
		['name' => 'page#zahlungen', 'url' => '/zahlungen', 'verb' => 'GET'],
		['name' => 'page#zahlungenUebersicht', 'url' => '/zahlungen-uebersicht', 'verb' => 'GET'],
		['name' => 'page#journal', 'url' => '/journal', 'verb' => 'GET'],
		['name' => 'page#profil', 'url' => '/profil', 'verb' => 'GET'],
		['name' => 'page#sepaDataCarrier', 'url' => '/sepa-datentraeger', 'verb' => 'GET'],
		['name' => 'page#backupStatus', 'url' => '/backup', 'verb' => 'GET'],
		['name' => 'api#appVersion', 'url' => '/api/version', 'verb' => 'GET'],
		['name' => 'api#uploadLimits', 'url' => '/api/upload-limits', 'verb' => 'GET'],
		['name' => 'api#getConfig', 'url' => '/api/config', 'verb' => 'GET'],
		['name' => 'api#updateConfig', 'url' => '/api/config', 'verb' => 'POST'],
		['name' => 'api#members', 'url' => '/api/members', 'verb' => 'GET'],
		['name' => 'api#users', 'url' => '/api/users', 'verb' => 'GET'],
		['name' => 'api#getMember', 'url' => '/api/member/{id}', 'verb' => 'GET'],
		['name' => 'api#updateMember', 'url' => '/api/member/{id}', 'verb' => 'PUT'],
		['name' => 'api#withdrawMandate', 'url' => '/api/member/{id}/withdraw', 'verb' => 'POST'],
		['name' => 'api#mandatePdf', 'url' => '/api/member/{id}/mandate-pdf', 'verb' => 'GET'],
		['name' => 'api#uploadSignedMandate', 'url' => '/api/member/{id}/mandate-signed', 'verb' => 'POST'],
		['name' => 'api#getSignedMandate', 'url' => '/api/member/{id}/mandate-signed', 'verb' => 'GET'],
		['name' => 'api#approveMandatePdf', 'url' => '/api/member/{id}/mandate-signed/{v}/approve', 'verb' => 'POST'],
		['name' => 'api#deleteSignedMandatePdf', 'url' => '/api/member/{id}/mandate-signed/{v}', 'verb' => 'DELETE'],
		['name' => 'api#downloadSignedMandate', 'url' => '/api/download/{id}', 'verb' => 'GET'],
		['name' => 'api#myGroups', 'url' => '/api/my-groups', 'verb' => 'GET'],
		['name' => 'api#myMember', 'url' => '/api/my-member', 'verb' => 'GET'],
		['name' => 'api#updateDisplayName', 'url' => '/api/update-display-name', 'verb' => 'POST'],
		['name' => 'api#assignUser', 'url' => '/api/assign', 'verb' => 'POST'],
		['name' => 'api#unassignUser', 'url' => '/api/unassign', 'verb' => 'POST'],
		['name' => 'api#vorschreibungPdf', 'url' => '/api/vorschreibung/{id}/{month}', 'verb' => 'GET'],
		['name' => 'api#getVorschreibungen', 'url' => '/api/vorschreibungen', 'verb' => 'GET'],
		['name' => 'api#generateVorschreibungen', 'url' => '/api/vorschreibungen/{year}/{month}/generate', 'verb' => 'POST'],
		['name' => 'api#zahlungenImport', 'url' => '/api/zahlungen/import', 'verb' => 'POST'],
		['name' => 'api#zahlungenAutoMatch', 'url' => '/api/zahlungen/auto-match', 'verb' => 'POST'],
		['name' => 'api#zahlungenGetUnmatched', 'url' => '/api/zahlungen/unmatched', 'verb' => 'GET'],
		['name' => 'api#zahlungenAssign', 'url' => '/api/zahlungen/{zahlungId}/assign/{memberId}', 'verb' => 'POST'],
		['name' => 'api#zahlungenUnassign', 'url' => '/api/zahlungen/{zahlungId}/unassign', 'verb' => 'POST'],
		['name' => 'api#zahlungenGet', 'url' => '/api/zahlungen', 'verb' => 'GET'],
		['name' => 'api#zahlungenUebersicht', 'url' => '/api/zahlungen-uebersicht', 'verb' => 'GET'],
		['name' => 'api#memberJournal', 'url' => '/api/member/{memberId}/journal', 'verb' => 'GET'],
		['name' => 'api#sepaDataCarrier', 'url' => '/api/sepa-datentraeger', 'verb' => 'GET'],
		['name' => 'api#sepaDataCarrierCsv', 'url' => '/api/sepa-datentraeger/export', 'verb' => 'GET'],
		['name' => 'api#exportUsersCSV', 'url' => '/api/export-users', 'verb' => 'GET'],
		['name' => 'api#exportUsersPDF', 'url' => '/api/export-users/pdf', 'verb' => 'GET'],
		['name' => 'api#exportMembersAttendancePDF', 'url' => '/api/export-users/attendance', 'verb' => 'GET'],
		['name' => 'api#pendingMandateApprovals', 'url' => '/api/pending-mandate-approvals', 'verb' => 'GET'],
		['name' => 'api#exportDatabase', 'url' => '/api/backup/export', 'verb' => 'GET'],
		['name' => 'api#getBackupStatus', 'url' => '/api/backup/status', 'verb' => 'GET'],
		['name' => 'api#downloadBackup', 'url' => '/api/backup/download/{filename}', 'verb' => 'GET'],
	],
];
